name: 'BUILD OVERLAY'
on: 
  workflow_dispatch:
  
jobs:
  build:
    name: 'Xem quá trình...'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Xem thông báo'
        run: |
          # Run Build 
          chmod 777 .github/* 2>/dev/null 
          export NG="$(date +"%y%m%d")"
          echo "PB=$NG" >> $GITHUB_ENV
          .github/Reo 2>&1 | tee -a log.txt
      - uses: actions/upload-artifact@v4
        with:
          name: overlay.zip
          path: signed/*
          retention-days: 3
      - name: Overlay
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Overlay_V1.${{ env.PB }}
          files: OV/*
          prerelease: true
      - name: Flash Overlay
        uses: softprops/action-gh-release@v2
        with:
          tag_name: VH_XIAOMI_TWRP_V1.${{ env.PB }}
          files: UP/*
          prerelease: true
      - name: Lưu Log
        uses: actions/upload-artifact@v4
        with:
         name: Xem Log
         path: log.txt
         retention-days: 5
